"""add novas tabelas

Revision ID: 9ee9efcbe0ab
Revises: e9e327f38c57
Create Date: 2026-07-03 23:43:13.660783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee9efcbe0ab'
down_revision: Union[str, Sequence[str], None] = 'e9e327f38c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aluno_id'), 'aluno', ['id'], unique=False)
    op.create_table('plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plano_id'), 'plano', ['id'], unique=False)
    op.create_table('mensalidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO', name='statusmensalidade'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['plano.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensalidade_id'), 'mensalidade', ['id'], unique=False)
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensalidade_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('comprovante_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mensalidade_id'], ['mensalidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamento_id'), 'pagamento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamento_id'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_index(op.f('ix_mensalidade_id'), table_name='mensalidade')
    op.drop_table('mensalidade')
    op.drop_index(op.f('ix_plano_id'), table_name='plano')
    op.drop_table('plano')
    op.drop_index(op.f('ix_aluno_id'), table_name='aluno')
    op.drop_table('aluno')
    # ### end Alembic commands ###
